source 'https://cdn.cocoapods.org'

platform :ios, '14.0'
use_frameworks!

target 'iosApp' do
  pod 'shared', :path => '../shared'
  pod 'Ably', '~> 1.2'
  pod 'GoogleWebRTC', '~> 1.1'
  pod 'CocoaMQTT', '~> 2.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_DEBUG_DYLIB'] = 'NO'
    end
  end
end